version: "3.9"

services:
  mysql:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "world"
    ports:
      - "3306:3306"
    restart: always
    networks:
      - mynet

  php:
    container_name: laravel_container
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    working_dir: /home/www/
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    depends_on:
      - mysql
    networks:
      - mynet

  web:
    container_name: nginx_container
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./laravel:/home/www
    links:
      - php
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
